# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'entities', '0001_initial'), (b'entities', '0002_auto_20160306_0146'), (b'entities', '0003_entity'), (b'entities', '0004_auto_20160306_0236'), (b'entities', '0005_auto_20160306_0441'), (b'entities', '0006_entityscore'), (b'entities', '0007_auto_20160308_1712'), (b'entities', '0008_entityscore_count')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Type')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('main_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_type', to='entities.Type')),
                ('sub_types', models.ManyToManyField(blank=True, related_name='sub_types', to=b'entities.Type')),
            ],
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'entities'},
        ),
        migrations.CreateModel(
            name='EntityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=6, max_digits=9)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='entities.Entity')),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
