# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='parent_topic',
            new_name='parent_type',
        ),
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
