# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20160306_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('main_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_type', to='entities.Type')),
                ('sub_types', models.ManyToManyField(blank=True, null=True, related_name='sub_types', to='entities.Type')),
            ],
        ),
    ]
