# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20160308_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='dbpedia',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='freebase',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='geo_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='geo_long',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='yago',
            field=models.URLField(blank=True, null=True),
        ),
    ]
