# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='sub_types',
            field=models.ManyToManyField(blank=True, related_name='sub_types', to='entities.Type'),
        ),
    ]
