# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20160306_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=6, max_digits=9)),
                ('entity', models.ManyToManyField(blank=True, related_name='entity', to='entities.Entity')),
            ],
        ),
    ]
