# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_userentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='twitter_user',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
