# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_entity_twitter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='facebook_user',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='hashtag',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='linkedin_user',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
