# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_auto_20160308_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityscore',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
