app:
  restart: always
  build: ./app
  expose:
    - "8000"
  links:
    - mysql:mysql
  volumes:
    - ./app:/usr/src/app
  env_file: .env
  environment:
    DEBUG: 'true'
  command: /usr/local/bin/gunicorn context.wsgi:application -w 2 -b :8000

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - app
  links:
    - app:app

mysql:
  restart: always
  env_file: .env
  image: mysql:latest
  ports:
    - "5432:5432"
  volumes:
    - ./volumes/mysql:/var/lib/mysql