# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [(b'feeds', '0001_initial'), (b'feeds', '0002_auto_20160301_1916')]

    initial = True

    dependencies = [
        ('articles', '0001_squashed_0023_remove_article_entities'),
    ]

    operations = [
    ]
