# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='global',
            name='articles',
        ),
        migrations.DeleteModel(
            name='Global',
        ),
    ]
