# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_microservice_user',
            field=models.BooleanField(default=False),
        ),
    ]
