# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_is_microservice_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email_extension', models.TextField()),
                ('active_subscription', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ManyToManyField(blank=True, to='users.Company'),
        ),
    ]
