# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0003_publisher_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('articles', models.ManyToManyField(to='articles.Article')),
            ],
        ),
    ]
