# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_squashed_0023_remove_article_entities'),
        ('timelines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('articles', models.ManyToManyField(to='articles.Article')),
            ],
        ),
    ]
