# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_squashed_0023_remove_article_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='opening_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
