# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_publisher_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='url',
            field=models.URLField(default='http://nytimes.com', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
