# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_opening_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
