# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20160105_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='has_paywall',
            field=models.BooleanField(default=False),
        ),
    ]
