# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_publisher_has_paywall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='basic_summary',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
