# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20160205_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
