# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_userarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticle',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
