# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20160205_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_url', models.URLField(max_length=255, unique=True)),
                ('publisher', models.ManyToManyField(blank=True, to='articles.Publisher')),
            ],
        ),
    ]
