# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 02:22
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_publisherfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='for_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
