# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_userarticle_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticle',
            name='read_later',
            field=models.BooleanField(default=False),
        ),
    ]
