# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
