# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_publisher_for_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='basic_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
