# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_userarticle_read_later'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['added_at']},
        ),
        migrations.AlterModelOptions(
            name='userarticle',
            options={'ordering': ['article__added_at']},
        ),
        migrations.AddField(
            model_name='author',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='publisherfeed',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userarticle',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
