# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 22:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0008_auto_20160420_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.BooleanField(default=False)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Publisher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterModelOptions(
            name='userarticle',
            options={'ordering': ['0article__added_at']},
        ),
    ]
