# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_publisherfeed_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='finished_processing',
            field=models.BooleanField(default=False),
        ),
    ]
