# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20160421_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublisher',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
