# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_finished_processing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('parent_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='publisherfeed',
            name='topic',
            field=models.ManyToManyField(blank=True, to='articles.Topic'),
        ),
    ]
