# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_userpublisher_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publisher_feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.PublisherFeed'),
        ),
    ]
