# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20160305_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisherfeed',
            name='topic',
        ),
        migrations.AddField(
            model_name='publisherfeed',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Topic'),
        ),
    ]
