# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_publisher_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticle',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
