# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0013_userarticle_reported'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPublisherFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.PublisherFeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
