# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_userpublisherfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='position',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, to='articles.Topic'),
        ),
    ]
