# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 01:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20160305_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 6, 1, 24, 42, 446698)),
            preserve_default=False,
        ),
    ]
