# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20160601_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='facebook_user',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin_user',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter_user',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='facebook_user',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='twitter_user',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
