# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20160601_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='topic',
            field=models.ManyToManyField(blank=True, to='articles.Topic'),
        ),
    ]
