# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_entity'),
        ('articles', '0016_article_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='entities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Entity'),
        ),
    ]
