# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_article_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='entities_processed',
            field=models.BooleanField(default=False),
        ),
    ]
