# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20160601_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='approved',
            field=models.CharField(choices=[('Twitter', 'Twitter'), ('RSS', 'RSS'), ('Reddit', 'Reddit')], default=b'RSS', max_length=20),
        ),
    ]
