# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20160306_0441'),
        ('articles', '0018_article_entities_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='entities',
        ),
        migrations.AddField(
            model_name='article',
            name='entities',
            field=models.ManyToManyField(blank=True, null=True, to='entities.Entity'),
        ),
    ]
