# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_article_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='approved',
            new_name='source',
        ),
    ]
