# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_auto_20160308_1712'),
        ('articles', '0019_auto_20160308_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='entityscores',
            field=models.ManyToManyField(blank=True, null=True, to='entities.EntityScore'),
        ),
    ]
