# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_article_entityscores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='entityscores',
            new_name='entity_scores',
        ),
    ]
