# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20160308_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='entities',
            field=models.ManyToManyField(blank=True, to='entities.Entity'),
        ),
        migrations.AlterField(
            model_name='article',
            name='entity_scores',
            field=models.ManyToManyField(blank=True, to='entities.EntityScore'),
        ),
    ]
