# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_auto_20160308_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='entities',
        ),
    ]
